// AUTH
export const AUTH_NAV_ITEMS = [
  { label: "About", url: "#" },
  { label: "Download the X app", url: "#" },
  { label: "Grok", url: "#" },
  { label: "Help Center", url: "#" },
  { label: "Terms of Service", url: "#" },
  { label: "Privacy Policy", url: "#" },
  { label: "Cookie Policy", url: "#" },
  { label: "Accessibility", url: "#" },
  { label: "Ads info", url: "#" },
  { label: "Blog", url: "#" },
  { label: "Careers", url: "#" },
  { label: "Brand Resources", url: "#" },
  { label: "Advertising", url: "#" },
  { label: "Marketing", url: "#" },
  { label: "X for Business", url: "#" },
  { label: "Developers", url: "#" },
  { label: "Directory", url: "#" },  
  { label: "Settings", url: "#" },
  { label: "©2025 M&M", url: "#" },
];
